import { CreateManyDto, CrudRequest, CrudRequestOptions, CrudService, GetManyDefaultResponse } from '@nestjsx/crud';
import { ParsedRequestParams } from '@nestjsx/crud-request';
import { ObjectLiteral, Repository, SelectQueryBuilder, DeepPartial } from 'typeorm';
export declare class TypeOrmCrudService<T> extends CrudService<T> {
    protected repo: Repository<T>;
    private entityColumns;
    private entityPrimaryColumns;
    private entityColumnsHash;
    private entityRelationsHash;
    constructor(repo: Repository<T>);
    readonly findOne: Repository<T>['findOne'];
    readonly find: Repository<T>['find'];
    readonly count: Repository<T>['count'];
    private readonly entityType;
    private readonly alias;
    getMany(req: CrudRequest): Promise<GetManyDefaultResponse<T> | T[]>;
    getOne(req: CrudRequest): Promise<T>;
    createOne(req: CrudRequest, dto: DeepPartial<T>): Promise<T>;
    createMany(req: CrudRequest, dto: CreateManyDto<DeepPartial<T>>): Promise<T[]>;
    updateOne(req: CrudRequest, dto: DeepPartial<T>): Promise<T>;
    replaceOne(req: CrudRequest, dto: DeepPartial<T>): Promise<T>;
    deleteOne(req: CrudRequest): Promise<void | T>;
    getParamFilters(parsed: CrudRequest['parsed']): ObjectLiteral;
    decidePagination(parsed: ParsedRequestParams, options: CrudRequestOptions): boolean;
    createBuilder(parsed: ParsedRequestParams, options: CrudRequestOptions, many?: boolean): Promise<SelectQueryBuilder<T>>;
    private getDefaultSearchCondition;
    private queryFilterToSearch;
    private onInitMapEntityColumns;
    private onInitMapRelations;
    private getOneOrFail;
    private getOneShallowOrFail;
    private prepareEntityBeforeSave;
    private getAllowedColumns;
    private getRelationMetadata;
    private setJoin;
    private setAndWhere;
    private setOrWhere;
    private setSearchCondition;
    private builderAddBrackets;
    private builderSetWhere;
    private setSearchFieldObjectCondition;
    private getSelect;
    private getSkip;
    private getTake;
    private getSort;
    private getFieldWithAlias;
    private mapSort;
    private mapOperatorsToQuery;
}
